services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mosquitto_network
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9004:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mosquitto_network


networks:
  mosquitto_network:
    driver: bridge